name: CI Seguro

on:
  push:
    branches:
      - Perfil
      - notificaciones

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Simular pruebas Perfil
        run: echo "Perfil OK"

      - name: Simular pruebas Notificaciones
        run: echo "Notificaciones OK"
